from django.db import models

# Create your models here.
class GameRecord(models.Model):
    GameMode     = models.TextChoices('GameMode', 'normal explore polyinit hah wizard')
    server       = models.CharField(max_length=128)
    variant      = models.CharField(max_length=128)
    version      = models.CharField(max_length=128)
    name         = models.CharField(max_length=128)
    role         = models.CharField(max_length=16)
    race         = models.CharField(max_length=16, null=True)
    gender       = models.CharField(max_length=16, null=True)
    align        = models.CharField(max_length=16, null=True)
    points       = models.BigIntegerField(null=True)
    turns        = models.BigIntegerField()
    realtime     = models.DurationField(null=True)
    wallclock    = models.DurationField(null=True)
    deathlev     = models.IntegerField(null=True)
    maxlvl       = models.IntegerField(null=True)
    hp           = models.BigIntegerField(null=True)
    maxhp        = models.BigIntegerField(null=True)
    starttime    = models.DateTimeField()
    endtime      = models.DateTimeField()
    death        = models.CharField(max_length=1024)
    align0       = models.CharField(max_length=16, null=True)
    gender0      = models.CharField(max_length=16, null=True)
    conducts     = models.CharField(max_length=4096, null=True, default='')
    achievements = models.CharField(max_length=4096, null=True, default='')
    won          = models.BooleanField(default=False)
    bonesless    = models.BooleanField(default=False)
    mode         = models.CharField(choices=GameMode.choices, default='normal', max_length=16)