# Generated by Django 3.1.6 on 2021-03-02 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('src_name', models.CharField(max_length=50)),
                ('last_check', models.DateTimeField(verbose_name='last accessed')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=10)),
                ('allowed_aligns', models.ManyToManyField(to='scoreboard.Alignment')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=10)),
                ('major', models.IntegerField(default=0)),
                ('minor', models.IntegerField(default=0)),
                ('patch', models.IntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=10)),
                ('allowed_aligns', models.ManyToManyField(to='scoreboard.Alignment')),
                ('allowed_races', models.ManyToManyField(to='scoreboard.Race')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.version')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.version'),
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=10)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.version')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(verbose_name='game start')),
                ('birthdate', models.DateField(verbose_name='birthday')),
                ('points', models.BigIntegerField(default=0)),
                ('maxlvl', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=0)),
                ('maxhp', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('turns', models.IntegerField(default=0)),
                ('realtime', models.IntegerField(default=0)),
                ('deathlev', models.IntegerField(default=0)),
                ('endtime', models.DateTimeField(verbose_name='game start')),
                ('deathdate', models.DateField(verbose_name='deathday')),
                ('align', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_ended', to='scoreboard.alignment')),
                ('align0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_started', to='scoreboard.alignment')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_ended', to='scoreboard.gender')),
                ('gender0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_started', to='scoreboard.gender')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.race')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.role')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.logsource')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.version')),
            ],
        ),
        migrations.AddField(
            model_name='alignment',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.version'),
        ),
    ]
