# Generated by Django 3.2.7 on 2021-10-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_turncount', models.IntegerField()),
                ('fastest_realtime', models.DurationField()),
                ('max_conducts_in_1_game', models.IntegerField()),
                ('max_ach_in_1_game', models.IntegerField()),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('longest_streak', models.IntegerField()),
                ('earliest_asc_time', models.DateTimeField()),
                ('unique_deaths', models.IntegerField()),
                ('unique_ascs', models.IntegerField()),
                ('games_over_1000_turns', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=32)),
                ('local_file', models.FilePathField(path='/home/stark/tnnt-python-backend/xlog')),
                ('file_pos', models.BigIntegerField()),
                ('last_check', models.DateTimeField()),
                ('location', models.URLField(null=True)),
                ('website', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_turncount', models.IntegerField()),
                ('fastest_realtime', models.DurationField()),
                ('max_conducts_in_1_game', models.IntegerField()),
                ('max_ach_in_1_game', models.IntegerField()),
                ('min_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('longest_streak', models.IntegerField()),
                ('earliest_asc_time', models.DateTimeField()),
                ('unique_deaths', models.IntegerField()),
                ('unique_ascs', models.IntegerField()),
                ('games_over_1000_turns', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoreboard.clan')),
                ('trophies', models.ManyToManyField(to='scoreboard.Trophy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=16)),
                ('race', models.CharField(max_length=16, null=True)),
                ('gender', models.CharField(max_length=16, null=True)),
                ('align', models.CharField(max_length=16, null=True)),
                ('points', models.BigIntegerField(null=True)),
                ('turns', models.BigIntegerField()),
                ('realtime', models.DurationField(null=True)),
                ('wallclock', models.DurationField(null=True)),
                ('deathlev', models.IntegerField(null=True)),
                ('maxlvl', models.IntegerField(null=True)),
                ('hp', models.BigIntegerField(null=True)),
                ('maxhp', models.BigIntegerField(null=True)),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('death', models.CharField(max_length=256)),
                ('align0', models.CharField(max_length=16, null=True)),
                ('gender0', models.CharField(max_length=16, null=True)),
                ('won', models.BooleanField(default=False)),
                ('bonesless', models.BooleanField(default=False)),
                ('achievements', models.ManyToManyField(to='scoreboard.Achievement')),
                ('conducts', models.ManyToManyField(to='scoreboard.Conduct')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.player')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scoreboard.source')),
            ],
        ),
        migrations.AddField(
            model_name='clan',
            name='trophies',
            field=models.ManyToManyField(to='scoreboard.Trophy'),
        ),
    ]
