# Generated by Django 3.1.6 on 2021-03-02 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignment',
            name='version',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='version',
        ),
    ]
