# Generated by Django 3.2.3 on 2021-08-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_gamerecord_death_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='align',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='gender',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='race',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='role',
            field=models.CharField(default='Valkyrie', max_length=16),
            preserve_default=False,
        ),
    ]
