# Generated by Django 3.2.8 on 2021-10-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_alter_source_local_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='website',
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='source',
            name='file_pos',
            field=models.BigIntegerField(default=0),
        ),
    ]
