# Generated by Django 3.1.6 on 2021-03-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_logsource_name_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_message',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logsource',
            name='file_cursor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logsource',
            name='records_imported',
            field=models.IntegerField(default=0),
        ),
    ]
