# Generated by Django 3.2.3 on 2021-08-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0003_auto_20210804_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerecord',
            old_name='player_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='server',
            field=models.CharField(default='asdf', max_length=128),
            preserve_default=False,
        ),
    ]
