# Generated by Django 3.2.3 on 2021-08-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20210804_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerecord',
            old_name='death_reason',
            new_name='death',
        ),
    ]
