# Generated by Django 3.1.6 on 2021-03-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0004_auto_20210302_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsource',
            name='local_path',
            field=models.FilePathField(default='/home/aoei/srcs/tnnt/python-backend/xlogs/<django.db.models.fields.CharField>'),
        ),
    ]
