# Generated by Django 3.1.6 on 2021-03-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_logsource_local_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='end_message',
            new_name='death',
        ),
        migrations.AddField(
            model_name='game',
            name='deathdnum',
            field=models.IntegerField(default=0),
        ),
    ]
