# Generated by Django 3.2.3 on 2021-08-04 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0005_rename_death_reason_gamerecord_death'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('long_name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=16)),
                ('bit_index', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='align0',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='gender0',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='points',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='realtime',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='turns',
            field=models.BigIntegerField(default=34252),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='conducts',
            field=models.ManyToManyField(to='scoreboard.Conduct'),
        ),
    ]
