# Generated by Django 3.2.3 on 2021-08-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0006_auto_20210804_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerecord',
            old_name='end_time',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='gamerecord',
            old_name='start_time',
            new_name='starttime',
        ),
    ]
