# Generated by Django 3.2.3 on 2021-08-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0008_auto_20210804_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='bonesless',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='explore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='wizmode',
            field=models.BooleanField(default=False),
        ),
    ]
