# Generated by Django 3.2.3 on 2021-08-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0010_conduct_achieve_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=128)),
                ('xlog_field', models.CharField(max_length=128)),
                ('bit_index', models.IntegerField()),
            ],
        ),
    ]
