# Generated by Django 3.2.3 on 2021-08-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0011_achievement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='description',
            new_name='descr',
        ),
    ]
