# Generated by Django 3.2.3 on 2021-08-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0013_rename_descr_achievement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
