# Generated by Django 3.2.3 on 2021-08-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0014_alter_achievement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='achievements',
            field=models.ManyToManyField(to='scoreboard.Achievement'),
        ),
    ]
