# Generated by Django 3.2.3 on 2021-08-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0015_gamerecord_achievements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerecord',
            old_name='win',
            new_name='won',
        ),
    ]
