# Generated by Django 3.2.3 on 2021-08-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0016_rename_win_gamerecord_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='deathlev',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='hp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='maxhp',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='maxlvl',
            field=models.IntegerField(null=True),
        ),
    ]
