# Generated by Django 3.2.3 on 2021-08-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0017_auto_20210805_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerecord',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='gamerecord',
            name='bonesless',
        ),
        migrations.RemoveField(
            model_name='gamerecord',
            name='explore',
        ),
        migrations.RemoveField(
            model_name='gamerecord',
            name='wizmode',
        ),
        migrations.RemoveField(
            model_name='gamerecord',
            name='won',
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='achieves',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.RemoveField(
            model_name='gamerecord',
            name='conducts',
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='conducts',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Conduct',
        ),
    ]
