# Generated by Django 3.2.3 on 2021-08-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0019_auto_20210806_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerecord',
            name='achieves',
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='achievements',
            field=models.CharField(default='', max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='conducts',
            field=models.CharField(default='', max_length=4096, null=True),
        ),
    ]
