# Generated by Django 3.2.3 on 2021-09-09 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0021_gamerecord_nconducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=128)),
                ('variant', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('local_file', models.FilePathField(path='/home/aoei/git/tnnt-dev/python-backend/xlog')),
                ('file_pos', models.BigIntegerField()),
                ('last_check', models.DateTimeField()),
                ('location', models.URLField(null=True)),
                ('website', models.URLField(null=True)),
                ('dumplog_fmt', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='gamerecord',
            name='server',
        ),
        migrations.RemoveField(
            model_name='gamerecord',
            name='variant',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.clan')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.player')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.gamerecord')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreboard.logsource')),
            ],
        ),
    ]
